/**
 * TS ↔ Python policy parity (SLS-30). The fixture is generated by
 * services/rl/scripts/export_policy.py from the SAME checkpoint that
 * produced booster_policy.json — any drift here means the deployed policy
 * is not the trained one.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Quat, Vec3 } from "@starship-catch-sim/physics";
import { describe, expect, it } from "vitest";

import {
  innerLoopGimbal,
  mlpForward,
  type RLPolicyArtifact,
} from "./rlController.js";

const here = dirname(fileURLToPath(import.meta.url));

const fixture = JSON.parse(
  readFileSync(join(here, "__fixtures__/rl_policy_parity.json"), "utf8"),
) as {
  observations_normalized: number[][];
  actions: number[][];
  pd_cases: {
    att_xyzw: [number, number, number, number];
    omega_body: [number, number, number];
    lean_x: number;
    lean_z: number;
    gimbal_pitch_yaw: [number, number];
  }[];
};

const artifact = JSON.parse(
  readFileSync(
    join(here, "../../../apps/web/public/models/booster_policy.json"),
    "utf8",
  ),
) as RLPolicyArtifact;

describe("RL policy TS/Python parity", () => {
  it("MLP forward matches the Python policy on fixed observations", () => {
    fixture.observations_normalized.forEach((obs, i) => {
      const out = mlpForward(artifact.mlp.layers, obs).map((v) =>
        Math.max(-1, Math.min(1, v)),
      );
      const expected = fixture.actions[i];
      out.forEach((v, j) => {
        // float32 fixture vs float64 TS math: 1e-4 absolute is ample for
        // actions in [-1, 1] while still catching any real transposition
        // or layout bug (those produce O(1) errors).
        expect(Math.abs(v - expected[j]), `obs ${i} action ${j}`).toBeLessThan(
          1e-4,
        );
      });
    });
  });

  it("inner-loop PD matches the Python env implementation", () => {
    for (const c of fixture.pd_cases) {
      const [qx, qy, qz, qw] = c.att_xyzw;
      const g = innerLoopGimbal(
        Quat.of(qx, qy, qz, qw),
        Vec3.of(...c.omega_body),
        c.lean_x,
        c.lean_z,
        artifact.inner_loop_pd.k_att,
        artifact.inner_loop_pd.k_rate,
        artifact.inner_loop_pd.max_gimbal_rad,
      );
      expect(Math.abs(g.pitch - c.gimbal_pitch_yaw[0])).toBeLessThan(1e-9);
      expect(Math.abs(g.yaw - c.gimbal_pitch_yaw[1])).toBeLessThan(1e-9);
    }
  });

  it("artifact sanity: 17-in, 4-out, tanh hidden layers", () => {
    const layers = artifact.mlp.layers;
    expect(layers[0].w[0].length).toBe(17);
    expect(layers[layers.length - 1].b.length).toBe(4);
    expect(layers.slice(0, -1).every((l) => l.activation === "tanh")).toBe(
      true,
    );
    expect(artifact.obs.scale.length).toBe(17);
  });
});
